
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/linux-64'


WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from include.mcmc_posterior import *
  File "/local/291047/include/mcmc_posterior.py", line 4, in <module>
    import pymc as pm
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/__init__.py", line 49, in <module>
    from pymc import _version, gp, ode, sampling
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/gp/__init__.py", line 15, in <module>
    from pymc.gp import cov, mean, util
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/gp/util.py", line 30, in <module>
    from pymc.distributions.distribution import Distribution
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/distributions/__init__.py", line 15, in <module>
    from pymc.distributions.bound import Bound
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/distributions/bound.py", line 23, in <module>
    from pymc.distributions.continuous import BoundedContinuous, bounded_cont_transform
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/distributions/continuous.py", line 59, in <module>
    from pymc.logprob.abstract import _logcdf_helper, _logprob_helper
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/logprob/__init__.py", line 37, in <module>
    from pymc.logprob.basic import (
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/logprob/basic.py", line 65, in <module>
    from pymc.logprob.rewriting import cleanup_ir, construct_ir_fgraph
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/logprob/rewriting.py", line 84, in <module>
    from pymc.logprob.utils import DiracDelta, indices_from_subtensor
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/logprob/utils.py", line 67, in <module>
    from pymc.util import makeiter
  File "/home/yanw/.local/lib/python3.8/site-packages/pymc/util.py", line 20, in <module>
    import arviz
  File "/home/yanw/.conda/envs/uncertain/lib/python3.8/site-packages/arviz/__init__.py", line 33, in <module>
ModuleNotFoundError: No module named 'arviz.data'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 3777 on node hpc-node01 exited on signal 7 (Bus error).
--------------------------------------------------------------------------
/tmp/slurmd/job291047/slurm_script: line 57: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
/tmp/slurmd/job291047/slurm_script: line 58: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.base_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.base_exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.prefix = '/home/yanw/.conda/envs/uncertain'
  sys.exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.path = [
    '/home/yanw/.conda/envs/uncertain/lib/python38.zip',
    '/home/yanw/.conda/envs/uncertain/lib/python3.8',
    '/home/yanw/.conda/envs/uncertain/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f1abbf24740 (most recent call first):
<no Python frame>
/tmp/slurmd/job291047/slurm_script: line 57: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
/tmp/slurmd/job291047/slurm_script: line 58: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.base_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.base_exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.prefix = '/home/yanw/.conda/envs/uncertain'
  sys.exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.path = [
    '/home/yanw/.conda/envs/uncertain/lib/python38.zip',
    '/home/yanw/.conda/envs/uncertain/lib/python3.8',
    '/home/yanw/.conda/envs/uncertain/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f48bbafb740 (most recent call first):
<no Python frame>
/tmp/slurmd/job291047/slurm_script: line 57: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
/tmp/slurmd/job291047/slurm_script: line 58: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.base_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.base_exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.prefix = '/home/yanw/.conda/envs/uncertain'
  sys.exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.path = [
    '/home/yanw/.conda/envs/uncertain/lib/python38.zip',
    '/home/yanw/.conda/envs/uncertain/lib/python3.8',
    '/home/yanw/.conda/envs/uncertain/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffa0311a740 (most recent call first):
<no Python frame>
/tmp/slurmd/job291047/slurm_script: line 57: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
/tmp/slurmd/job291047/slurm_script: line 58: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.base_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.base_exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.prefix = '/home/yanw/.conda/envs/uncertain'
  sys.exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.path = [
    '/home/yanw/.conda/envs/uncertain/lib/python38.zip',
    '/home/yanw/.conda/envs/uncertain/lib/python3.8',
    '/home/yanw/.conda/envs/uncertain/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f4daea46740 (most recent call first):
<no Python frame>
/tmp/slurmd/job291047/slurm_script: line 57: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
/tmp/slurmd/job291047/slurm_script: line 58: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.base_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.base_exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.prefix = '/home/yanw/.conda/envs/uncertain'
  sys.exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.path = [
    '/home/yanw/.conda/envs/uncertain/lib/python38.zip',
    '/home/yanw/.conda/envs/uncertain/lib/python3.8',
    '/home/yanw/.conda/envs/uncertain/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f0d46899740 (most recent call first):
<no Python frame>
/tmp/slurmd/job291047/slurm_script: line 57: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
/tmp/slurmd/job291047/slurm_script: line 58: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.base_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.base_exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.executable = '/home/yanw/.conda/envs/uncertain/bin/python3.8'
  sys.prefix = '/home/yanw/.conda/envs/uncertain'
  sys.exec_prefix = '/home/yanw/.conda/envs/uncertain'
  sys.path = [
    '/home/yanw/.conda/envs/uncertain/lib/python38.zip',
    '/home/yanw/.conda/envs/uncertain/lib/python3.8',
    '/home/yanw/.conda/envs/uncertain/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fe8951d6740 (most recent call first):
<no Python frame>
/tmp/slurmd/job291047/slurm_script: line 67: /home/yanw/uncertain/results/log/0605/291047_version.log: No such file or directory
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0605'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
